### ISSUE TITLE
error for install openccg in ubuntu

### ISSUE THREAD

**Issue by yuquanle** [OpenCCG/openccg#14]
Hi everyone,
     I have some error, can you help me?
     1. I have following this https://davehowcroft.com/post/installing-openccg/,
     but in last next(./bin/ccg-build):
     I use : ./bin/ccg-build ，the error is : ./bin/ccg-build: 2: .: ccg-env: not found
     I use : bash ccg-build , the error is :Buildfile: build.xml does not exist!   Build failed
                                                                                                                         best wish！

**Comment by dmhowcroft** [comment]
Did you make an environment variable called OPENCCG_HOME for your OpenCCG install directory?

For example `export OPENCCG_HOME=/path/to/openccg`. (And add it to your `.bashrc` so the environment variable persists.)

It's also recommended to add `${OPENCCG_HOME}/bin` to your `PATH` environment variable so that `bash` can find `ccg-build` and `ccg-env` without having to add the location prefixes to tell it where to find those files. (`ccg-env` is in `bin/`, along with `ccg-build`)

**Comment by yuquanle** [comment]
Thanks very much
